import type { CourseTemplate } from '@/types/travel';

export const COURSES: Record<string, CourseTemplate> = {
  'seoul-2n3d-couple': {
    id: 'seoul-2n3d-couple',
    regionId: 'seoul',
    slug: '2박3일-커플',
    title: '서울 2박3일 커플 여행 코스',
    summary: '도보와 지하철 위주로 이동 가능한 감성 코스',
    tripLength: { nights: 2, days: 3 },
    companions: ['couple'],
    themes: ['cafe', 'culture', 'food', 'city'],
    mobility: 'transit',
    weatherFit: ['all', 'rain-friendly'],
    budget: {
      min: 400000,
      max: 600000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'mid',
      text: '40~60만원',
    },
    difficulty: 1,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '10:00', placeId: 'ikseondong' },
          { time: '12:00', placeId: 'gwangjang-market' },
          { time: '15:00', placeId: 'seongsu' },
        ],
      },
      {
        title: 'Day 2',
        schedule: [
          { time: '10:30', placeId: 'bukchon' },
          { time: '13:00', placeId: 'ikseondong' },
          { time: '18:00', placeId: 'seongsu' },
        ],
      },
      {
        title: 'Day 3',
        schedule: [
          { time: '09:30', placeId: 'gwangjang-market' },
          { time: '12:30', placeId: 'bukchon' },
        ],
      },
    ],
    tips: [
      '주말은 익선동 웨이팅이 길어 오전 방문이 유리합니다.',
      '대중교통 이동 기준 하루 15,000원 교통비를 잡으면 안정적입니다.',
    ],
  },
  'seoul-1day-city': {
    id: 'seoul-1day-city',
    regionId: 'seoul',
    slug: '당일치기-도심',
    title: '서울 당일치기 코스',
    summary: '아침부터 저녁까지 압축한 도심 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['friends', 'family'],
    themes: ['food', 'culture', 'city'],
    mobility: 'walk',
    weatherFit: ['all', 'rain-friendly'],
    budget: {
      min: 120000,
      max: 200000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'low',
      text: '12~20만원',
    },
    difficulty: 2,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '09:00', placeId: 'gwangjang-market' },
          { time: '11:30', placeId: 'bukchon' },
          { time: '15:00', placeId: 'ikseondong' },
        ],
      },
    ],
    tips: ['도보 이동량이 많아 편한 신발을 권장합니다.'],
  },
  'seoul-palace-river-1day': {
    id: 'seoul-palace-river-1day',
    regionId: 'seoul',
    slug: '궁궐-한강-하루',
    title: '서울 궁궐·한강 하루 코스',
    summary: '북촌에서 시작해 광화문과 한강 야경까지 이어지는 클래식 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['parents', 'family', 'couple'],
    themes: ['culture', 'history', 'night-view', 'city'],
    mobility: 'transit',
    weatherFit: ['sunny', 'cloudy'],
    budget: {
      min: 150000,
      max: 250000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'low',
      text: '15~25만원',
    },
    difficulty: 2,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '09:30', placeId: 'bukchon' },
          { time: '12:00', placeId: 'gwanghwamun-square' },
          { time: '18:30', placeId: 'banpo-hangang-park' },
        ],
      },
    ],
    tips: [
      '광화문 일대는 전시나 행사 여부에 따라 체류 시간이 늘어날 수 있습니다.',
      '반포한강공원은 저녁 바람이 강해 겉옷을 챙기면 편합니다.',
    ],
  },
  'busan-east-west-1n2d': {
    id: 'busan-east-west-1n2d',
    regionId: 'busan',
    slug: '1박2일-바다-감성',
    title: '부산 1박2일 바다·감성 코스',
    summary: '감천문화마을과 영도, 해운대를 잇는 첫 부산 여행 코스',
    tripLength: { nights: 1, days: 2 },
    companions: ['couple', 'friends'],
    themes: ['ocean', 'culture', 'city'],
    mobility: 'transit',
    weatherFit: ['sunny', 'cloudy'],
    budget: {
      min: 200000,
      max: 350000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'mid',
      text: '20~35만원',
    },
    difficulty: 2,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '10:30', placeId: 'gamcheon-village' },
          { time: '14:30', placeId: 'huinnyeoul-tunnel' },
        ],
      },
      {
        title: 'Day 2',
        schedule: [{ time: '16:00', placeId: 'haeundae-beach' }],
      },
    ],
    tips: [
      '감천문화마을은 주민 거주지라 조용히 이동하는 편이 좋습니다.',
      '영도와 해운대는 이동 거리가 있어 대중교통 또는 택시 동선을 미리 잡아두면 편합니다.',
    ],
  },
  'busan-night-view-1day': {
    id: 'busan-night-view-1day',
    regionId: 'busan',
    slug: '야경-해변-하루',
    title: '부산 야경·해변 하루 코스',
    summary: '흰여울과 광안리, 해운대까지 이어지는 저녁 중심 부산 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['couple', 'friends'],
    themes: ['night-view', 'ocean', 'cafe'],
    mobility: 'transit',
    weatherFit: ['sunny', 'cloudy'],
    budget: {
      min: 120000,
      max: 240000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'low',
      text: '12~24만원',
    },
    difficulty: 1,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '14:00', placeId: 'huinnyeoul-tunnel' },
          { time: '17:30', placeId: 'gwangalli-beach' },
          { time: '20:00', placeId: 'haeundae-beach' },
        ],
      },
    ],
    tips: [
      '광안리와 해운대 모두 저녁 시간대 보행 인구가 많아 이동 시간을 넉넉히 잡는 편이 좋습니다.',
      '야경 촬영 위주라면 해 질 무렵부터 2시간 정도 여유를 두는 구성이 편합니다.',
    ],
  },
  'jeju-east-coast-1day': {
    id: 'jeju-east-coast-1day',
    regionId: 'jeju',
    slug: '동부-하루',
    title: '제주 동부 하루 코스',
    summary: '성산일출봉, 섭지코지, 우도를 중심으로 묶은 동부 핵심 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['couple', 'friends', 'family'],
    themes: ['nature', 'ocean', 'drive'],
    mobility: 'car',
    weatherFit: ['sunny', 'cloudy'],
    budget: {
      min: 150000,
      max: 300000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'mid',
      text: '15~30만원',
    },
    difficulty: 2,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '08:00', placeId: 'seongsan-ilchulbong' },
          { time: '11:30', placeId: 'seopjikoji' },
          { time: '14:30', placeId: 'udo-island' },
        ],
      },
    ],
    tips: [
      '성산일출봉은 계절별 운영시간이 달라 출발 전에 공식 안내를 다시 확인하는 편이 안전합니다.',
      '우도는 배편 시간과 차량 선적 여부에 따라 체류 시간이 크게 달라질 수 있습니다.',
    ],
  },
  'jeju-west-drive-1day': {
    id: 'jeju-west-drive-1day',
    regionId: 'jeju',
    slug: '서부-드라이브-하루',
    title: '제주 서부 드라이브 코스',
    summary: '오설록과 협재, 한림공원을 중심으로 짠 여유로운 서부 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['couple', 'friends', 'parents', 'kids', 'family'],
    themes: ['drive', 'nature', 'healing'],
    mobility: 'car',
    weatherFit: ['all', 'rain-friendly'],
    budget: {
      min: 180000,
      max: 320000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'mid',
      text: '18~32만원',
    },
    difficulty: 1,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '10:00', placeId: 'osulloc' },
          { time: '13:30', placeId: 'hyeopjae-beach' },
          { time: '16:00', placeId: 'hallim-park' },
        ],
      },
    ],
    tips: [
      '서부 해안은 바람이 강한 날이 많아 해변 체류 시간을 유연하게 잡는 편이 좋습니다.',
      '카페와 디저트 코스를 함께 넣으면 체감 만족도가 높습니다.',
    ],
  },
  'gangneung-coast-1day': {
    id: 'gangneung-coast-1day',
    regionId: 'gangneung',
    slug: '바다-문화-하루',
    title: '강릉 바다·문화 하루 코스',
    summary: '오죽헌에서 시작해 경포와 안목해변까지 이어지는 강릉 대표 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['parents', 'family', 'friends'],
    themes: ['ocean', 'culture', 'food'],
    mobility: 'car',
    weatherFit: ['sunny', 'cloudy'],
    budget: {
      min: 100000,
      max: 220000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'low',
      text: '10~22만원',
    },
    difficulty: 1,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '10:00', placeId: 'ojukheon' },
          { time: '13:30', placeId: 'gyeongpo-beach' },
          { time: '17:00', placeId: 'anmok-beach' },
        ],
      },
    ],
    tips: [
      '오죽헌은 실내 관람 마감 시간이 있으니 늦은 오후 방문은 피하는 편이 좋습니다.',
      '안목해변은 주말 주차가 빠르게 차는 편이라 늦은 오후에는 도보 이동이 편할 수 있습니다.',
    ],
  },
  'gangneung-cafe-healing-1day': {
    id: 'gangneung-cafe-healing-1day',
    regionId: 'gangneung',
    slug: '카페-힐링-하루',
    title: '강릉 카페·힐링 하루 코스',
    summary: '초당과 안목, 경포호를 여유롭게 잇는 감성 중심 강릉 코스',
    tripLength: { nights: 0, days: 1 },
    companions: ['solo', 'friends', 'couple'],
    themes: ['cafe', 'healing', 'food', 'ocean'],
    mobility: 'car',
    weatherFit: ['all', 'rain-friendly'],
    budget: {
      min: 110000,
      max: 240000,
      currency: 'KRW',
      basis: 'perTrip',
      level: 'low',
      text: '11~24만원',
    },
    difficulty: 1,
    days: [
      {
        title: 'Day 1',
        schedule: [
          { time: '10:30', placeId: 'chodang-sundubu-village' },
          { time: '13:30', placeId: 'gyeongpo-beach' },
          { time: '16:30', placeId: 'anmok-beach' },
        ],
      },
    ],
    tips: [
      '초당 순두부 마을은 점심 시간 대기가 길 수 있어 조금 이른 방문이 유리합니다.',
      '안목 카페거리는 해 질 무렵 이후 좌석 대기가 생길 수 있습니다.',
    ],
  },
};

export const COURSE_IDS = Object.keys(COURSES);
export const courseList = COURSE_IDS.map((id) => COURSES[id]);
