import type { LandingPage } from '@/types/travel';

export const LANDINGS: Record<string, LandingPage> = {
  'gangneung-1박2일': {
    id: 'gangneung-1박2일',
    regionId: 'gangneung',
    slug: '1박2일',
    indexable: true,
    intent: { nights: 1, days: 2 },
    heroTitle: '강릉 1박2일 여행 코스',
    heroDescription:
      '바다와 카페, 로컬 먹거리를 균형 있게 담은 강릉 1박2일 일정 가이드',
    intro:
      'KTX 또는 자차로 접근하기 쉽고, 바다와 카페 동선이 촘촘해 첫 강릉 여행에 특히 잘 맞는 구성을 담았습니다.',
    highlights: [
      '서울 출발 이동 시간 기준 추천 출발 시각',
      '초당-경포-안목 중심 핵심 동선',
      '당일보다 여유 있는 카페 체류 전략',
    ],
    courseIds: ['gangneung-coast-1day', 'gangneung-cafe-healing-1day'],
    featuredPlaceIds: [
      'ojukheon',
      'gyeongpo-beach',
      'anmok-beach',
      'chodang-sundubu-village',
    ],
    relatedLandingIds: ['gangneung-비오는날', 'gangneung-카페힐링'],
    updatedAt: '2026-02-19',
  },
  'gangneung-비오는날': {
    id: 'gangneung-비오는날',
    regionId: 'gangneung',
    slug: '비오는날',
    indexable: true,
    intent: { weatherFit: ['rain-friendly'] },
    heroTitle: '강릉 비오는날 여행 코스',
    heroDescription:
      '오죽헌과 초당 카페, 순두부 마을 중심으로 짠 우천 대체 강릉 일정',
    intro:
      '해변 체류를 줄이고 실내 비중을 높여도 강릉 특유의 분위기와 먹거리 만족도를 놓치지 않는 구성입니다.',
    highlights: [
      '실내 전시와 카페 위주 대체 동선',
      '비 오는 날 체류 만족도가 높은 장소 위주 선정',
    ],
    courseIds: ['gangneung-cafe-healing-1day'],
    featuredPlaceIds: ['ojukheon', 'chodang-sundubu-village', 'anmok-beach'],
    relatedLandingIds: ['gangneung-1박2일'],
    updatedAt: '2026-02-19',
  },
  'gangneung-카페힐링': {
    id: 'gangneung-카페힐링',
    regionId: 'gangneung',
    slug: '카페힐링',
    indexable: true,
    intent: { themes: ['cafe', 'healing'] },
    heroTitle: '강릉 카페 힐링 여행',
    heroDescription:
      '안목과 초당을 중심으로 여유롭게 쉬는 강릉 카페 여행 가이드',
    courseIds: ['gangneung-cafe-healing-1day'],
    featuredPlaceIds: [
      'anmok-beach',
      'chodang-sundubu-village',
      'gyeongpo-beach',
    ],
    relatedLandingIds: ['gangneung-1박2일'],
    updatedAt: '2026-02-19',
  },
  'busan-1박2일': {
    id: 'busan-1박2일',
    regionId: 'busan',
    slug: '1박2일',
    indexable: true,
    intent: { nights: 1, days: 2 },
    heroTitle: '부산 1박2일 여행 코스',
    heroDescription: '감천, 영도, 해운대를 한 번에 담는 첫 부산 1박2일 일정',
    courseIds: ['busan-east-west-1n2d'],
    featuredPlaceIds: [
      'gamcheon-village',
      'huinnyeoul-tunnel',
      'haeundae-beach',
    ],
    relatedLandingIds: ['busan-비오는날', 'busan-야경하루'],
    updatedAt: '2026-02-19',
  },
  'busan-비오는날': {
    id: 'busan-비오는날',
    regionId: 'busan',
    slug: '비오는날',
    indexable: true,
    intent: { weatherFit: ['rain-friendly'] },
    heroTitle: '부산 비오는날 여행 코스',
    heroDescription:
      '실내 카페와 먹거리 중심으로 부산의 분위기를 즐기는 우천 대체 동선',
    highlights: [
      '해변 체류를 줄이고 카페와 식사 중심으로 재구성',
      '비 오는 날에도 사진 남기기 좋은 영도 일대 추천',
    ],
    courseIds: [],
    featuredPlaceIds: ['huinnyeoul-tunnel', 'gwangalli-beach'],
    relatedLandingIds: ['busan-1박2일'],
    updatedAt: '2026-02-19',
  },
  'busan-야경하루': {
    id: 'busan-야경하루',
    regionId: 'busan',
    slug: '야경하루',
    indexable: true,
    intent: { days: 1, themes: ['night-view'] },
    heroTitle: '부산 야경 하루 코스',
    heroDescription:
      '광안리와 해운대를 중심으로 저녁 시간 효율을 높인 부산 야경 여행',
    courseIds: ['busan-night-view-1day'],
    featuredPlaceIds: [
      'huinnyeoul-tunnel',
      'gwangalli-beach',
      'haeundae-beach',
    ],
    relatedLandingIds: ['busan-1박2일'],
    updatedAt: '2026-02-19',
  },
  'seoul-2박3일-커플': {
    id: 'seoul-2박3일-커플',
    regionId: 'seoul',
    slug: '2박3일-커플',
    indexable: true,
    intent: { nights: 2, days: 3, companions: ['couple'] },
    heroTitle: '서울 2박3일 커플 여행 코스',
    heroDescription:
      '익선동, 성수, 한강 야경까지 감성 밀도가 높은 서울 커플 일정',
    courseIds: ['seoul-2n3d-couple'],
    featuredPlaceIds: ['ikseondong', 'seongsu', 'banpo-hangang-park'],
    relatedLandingIds: ['seoul-당일치기'],
    updatedAt: '2026-02-19',
  },
  'seoul-당일치기': {
    id: 'seoul-당일치기',
    regionId: 'seoul',
    slug: '당일치기',
    indexable: true,
    intent: { days: 1, mobility: ['walk', 'transit'] },
    heroTitle: '서울 당일치기 여행',
    heroDescription: '광장시장부터 북촌, 익선동까지 하루에 묶는 서울 압축 코스',
    courseIds: ['seoul-1day-city', 'seoul-palace-river-1day'],
    featuredPlaceIds: [
      'gwangjang-market',
      'bukchon',
      'ikseondong',
      'gwanghwamun-square',
    ],
    relatedLandingIds: ['seoul-2박3일-커플'],
    updatedAt: '2026-02-19',
  },
  'jeju-동부하루': {
    id: 'jeju-동부하루',
    regionId: 'jeju',
    slug: '동부하루',
    indexable: true,
    intent: { days: 1, themes: ['nature', 'ocean'] },
    heroTitle: '제주 동부 하루 여행',
    heroDescription:
      '성산일출봉과 섭지코지, 우도를 중심으로 짠 제주 동부 핵심 일정',
    courseIds: ['jeju-east-coast-1day'],
    featuredPlaceIds: ['seongsan-ilchulbong', 'seopjikoji', 'udo-island'],
    relatedLandingIds: ['jeju-서부드라이브'],
    updatedAt: '2026-02-19',
  },
  'jeju-서부드라이브': {
    id: 'jeju-서부드라이브',
    regionId: 'jeju',
    slug: '서부드라이브',
    indexable: true,
    intent: { days: 1, mobility: ['car'], themes: ['drive'] },
    heroTitle: '제주 서부 드라이브 코스',
    heroDescription:
      '오설록, 협재, 한림공원을 여유롭게 잇는 제주 서부 감성 드라이브',
    courseIds: ['jeju-west-drive-1day'],
    featuredPlaceIds: ['osulloc', 'hyeopjae-beach', 'hallim-park'],
    relatedLandingIds: ['jeju-동부하루'],
    updatedAt: '2026-02-19',
  },
};

export const LANDING_IDS = Object.keys(LANDINGS);
export const landingList = LANDING_IDS.map((id) => LANDINGS[id]);
