import type { RegionPlace } from '@/types/travel';

export const PLACES: Record<string, RegionPlace> = {
  ikseondong: {
    id: 'ikseondong',
    regionId: 'seoul',
    slug: 'ikseondong',
    name: '익선동 한옥거리',
    address: '서울 종로구 익선동 일대',
    category: 'street',
    themes: ['cafe', 'culture', 'food', 'city'],
    companions: ['solo', 'couple', 'friends'],
    weatherFit: ['all', 'rain-friendly'],
    hoursText: '상점별 상이 (대부분 11:00~22:00)',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['morning', 'afternoon', 'evening'],
    bestVisitText: '평일 오전 11시 이전',
    tips: [
      '골목 안쪽 카페는 오픈 직후가 가장 한산합니다.',
      '야간 조명 스팟은 해질 무렵 촬영이 좋습니다.',
    ],
    nearbyPlaceIds: ['gwangjang-market', 'bukchon'],
    legacy: {
      hours: '상점별 상이 (대부분 11:00~22:00)',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '평일 오전 11시 이전',
      nearbyPlaceSlugs: ['gwangjang-market', 'bukchon'],
      includedCourseSlugs: ['2n3d-couple', '1day-city'],
    },
  },
  'gwangjang-market': {
    id: 'gwangjang-market',
    regionId: 'seoul',
    slug: 'gwangjang-market',
    name: '광장시장',
    address: '서울 종로구 창경궁로 88',
    category: 'market',
    themes: ['food', 'culture', 'city'],
    companions: ['solo', 'couple', 'friends', 'parents', 'family'],
    weatherFit: ['all', 'rain-friendly', 'indoor'],
    hoursText: '09:00~23:00',
    feeText: '무료',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['morning', 'lunch'],
    bestVisitText: '오전 9시~11시',
    tips: [
      '점심 피크타임 전 방문 시 대기 시간이 짧습니다.',
      '현금 결제가 편한 가게가 일부 있습니다.',
    ],
    nearbyPlaceIds: ['ikseondong', 'seongsu'],
    legacy: {
      hours: '09:00~23:00',
      fee: '무료',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오전 9시~11시',
      nearbyPlaceSlugs: ['ikseondong', 'seongsu'],
      includedCourseSlugs: ['2n3d-couple', '1day-city'],
    },
  },
  seongsu: {
    id: 'seongsu',
    regionId: 'seoul',
    slug: 'seongsu',
    name: '성수 카페거리',
    address: '서울 성동구 성수동 일대',
    category: 'cafe-area',
    themes: ['cafe', 'shopping', 'city'],
    companions: ['solo', 'couple', 'friends'],
    weatherFit: ['all', 'rain-friendly'],
    hoursText: '상점별 상이 (대부분 10:00~21:00)',
    feeText: '무료',
    stayMinutes: { min: 120, max: 120 },
    bestTimeSlots: ['afternoon', 'evening'],
    bestVisitText: '평일 오후 2시 전',
    tips: [
      '브런치 매장은 사전 예약 가능 여부를 확인하세요.',
      '주말은 주차보다 지하철 접근이 빠릅니다.',
    ],
    nearbyPlaceIds: ['ikseondong', 'gwangjang-market'],
    legacy: {
      hours: '상점별 상이 (대부분 10:00~21:00)',
      fee: '무료',
      stayDuration: '2시간',
      bestVisitTime: '평일 오후 2시 전',
      nearbyPlaceSlugs: ['ikseondong', 'gwangjang-market'],
      includedCourseSlugs: ['2n3d-couple'],
    },
  },
  bukchon: {
    id: 'bukchon',
    regionId: 'seoul',
    slug: 'bukchon',
    name: '북촌 한옥마을',
    address: '서울 종로구 계동길 일대',
    category: 'village',
    themes: ['culture', 'history', 'city'],
    companions: ['solo', 'couple', 'friends', 'parents'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 90, max: 90 },
    bestTimeSlots: ['morning'],
    bestVisitText: '오전 9시~10시 30분',
    tips: [
      '주거 지역이 있어 정숙 관람이 필요합니다.',
      '오르막 구간이 있어 편한 신발이 좋습니다.',
    ],
    nearbyPlaceIds: ['ikseondong', 'gwangjang-market'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '1.5시간',
      bestVisitTime: '오전 9시~10시 30분',
      nearbyPlaceSlugs: ['ikseondong', 'gwangjang-market'],
      includedCourseSlugs: ['2n3d-couple', '1day-city'],
    },
  },
  'gwanghwamun-square': {
    id: 'gwanghwamun-square',
    regionId: 'seoul',
    slug: 'gwanghwamun-square',
    name: '광화문광장',
    address: '서울 종로구 세종대로 172',
    category: 'square',
    themes: ['culture', 'history', 'city'],
    companions: ['solo', 'couple', 'friends', 'parents', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 40, max: 60 },
    bestTimeSlots: ['morning', 'evening'],
    bestVisitText: '오전 10시 이전 또는 저녁',
    tips: [
      '주말 행사 여부에 따라 광장 동선이 달라질 수 있습니다.',
      '경복궁, 청계천과 묶으면 도보 동선이 자연스럽습니다.',
    ],
    nearbyPlaceIds: ['bukchon', 'banpo-hangang-park'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '40분~1시간',
      bestVisitTime: '오전 10시 이전 또는 저녁',
      nearbyPlaceSlugs: ['bukchon', 'banpo-hangang-park'],
      includedCourseSlugs: ['seoul-palace-river-1day'],
    },
  },
  'banpo-hangang-park': {
    id: 'banpo-hangang-park',
    regionId: 'seoul',
    slug: 'banpo-hangang-park',
    name: '반포한강공원',
    address: '서울 서초구 신반포로11길 40',
    category: 'park',
    themes: ['nature', 'night-view', 'healing', 'city'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['evening', 'night'],
    bestVisitText: '해질 무렵 이후',
    tips: [
      '돗자리나 가벼운 간식을 준비하면 체류 만족도가 높습니다.',
      '주말 저녁은 주차보다 대중교통 접근이 수월합니다.',
    ],
    nearbyPlaceIds: ['gwanghwamun-square', 'seongsu'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '해질 무렵 이후',
      nearbyPlaceSlugs: ['gwanghwamun-square', 'seongsu'],
      includedCourseSlugs: ['seoul-palace-river-1day'],
    },
  },
  'gamcheon-village': {
    id: 'gamcheon-village',
    regionId: 'busan',
    slug: 'gamcheon-village',
    name: '감천문화마을',
    address: '부산 사하구 감내2로 203',
    category: 'village',
    themes: ['culture', 'city', 'healing'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '3~10월 09:00~18:00, 11~2월 09:00~17:00',
    feeText: '무료',
    stayMinutes: { min: 90, max: 120 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '평일 오전 또는 늦은 오후',
    tips: [
      '골목이 좁고 경사가 있어 편한 신발이 유리합니다.',
      '실제 거주 지역이라 큰 소음은 피하는 편이 좋습니다.',
    ],
    nearbyPlaceIds: ['huinnyeoul-tunnel', 'haeundae-beach'],
    legacy: {
      hours: '3~10월 09:00~18:00, 11~2월 09:00~17:00',
      fee: '무료',
      stayDuration: '1.5~2시간',
      bestVisitTime: '평일 오전 또는 늦은 오후',
      nearbyPlaceSlugs: ['huinnyeoul-tunnel', 'haeundae-beach'],
      includedCourseSlugs: ['busan-east-west-1n2d'],
    },
  },
  'huinnyeoul-tunnel': {
    id: 'huinnyeoul-tunnel',
    regionId: 'busan',
    slug: 'huinnyeoul-tunnel',
    name: '흰여울해안터널',
    address: '부산 영도구 영선동4가 1210-38',
    category: 'street',
    themes: ['ocean', 'night-view', 'healing'],
    companions: ['solo', 'couple', 'friends'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '연중 개방',
    feeText: '무료',
    stayMinutes: { min: 40, max: 60 },
    bestTimeSlots: ['afternoon', 'evening'],
    bestVisitText: '오후 3시 이후',
    tips: [
      '해안 산책로와 함께 보면 체감 체류 시간이 길어집니다.',
      '터널 내부는 사진 촬영 대기 인원이 생길 수 있습니다.',
    ],
    nearbyPlaceIds: ['gamcheon-village', 'haeundae-beach'],
    legacy: {
      hours: '연중 개방',
      fee: '무료',
      stayDuration: '40분~1시간',
      bestVisitTime: '오후 3시 이후',
      nearbyPlaceSlugs: ['gamcheon-village', 'haeundae-beach'],
      includedCourseSlugs: ['busan-east-west-1n2d'],
    },
  },
  'haeundae-beach': {
    id: 'haeundae-beach',
    regionId: 'busan',
    slug: 'haeundae-beach',
    name: '해운대해수욕장',
    address: '부산 해운대구 해운대해변로 264',
    category: 'beach',
    themes: ['ocean', 'night-view', 'city'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['evening', 'night'],
    bestVisitText: '해질 무렵',
    tips: [
      '일몰 시간대에는 해변과 빌딩 스카이라인을 함께 보기 좋습니다.',
      '성수기와 주말에는 해변 주변 보행 인구가 많아 이동 시간이 길어질 수 있습니다.',
    ],
    nearbyPlaceIds: ['gamcheon-village', 'huinnyeoul-tunnel'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '해질 무렵',
      nearbyPlaceSlugs: ['gamcheon-village', 'huinnyeoul-tunnel'],
      includedCourseSlugs: ['busan-east-west-1n2d'],
    },
  },
  'gwangalli-beach': {
    id: 'gwangalli-beach',
    regionId: 'busan',
    slug: 'gwangalli-beach',
    name: '광안리해수욕장',
    address: '부산 수영구 광안해변로 219',
    category: 'beach',
    themes: ['ocean', 'night-view', 'cafe'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['evening', 'night'],
    bestVisitText: '해질 무렵 이후',
    tips: [
      '광안대교 점등 시간 전후가 가장 사진 찍기 좋습니다.',
      '해변 산책로와 카페 거리를 함께 보면 체류 시간이 길어질 수 있습니다.',
    ],
    nearbyPlaceIds: ['haeundae-beach', 'huinnyeoul-tunnel'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '해질 무렵 이후',
      nearbyPlaceSlugs: ['haeundae-beach', 'huinnyeoul-tunnel'],
      includedCourseSlugs: ['busan-night-view-1day'],
    },
  },
  'seongsan-ilchulbong': {
    id: 'seongsan-ilchulbong',
    regionId: 'jeju',
    slug: 'seongsan-ilchulbong',
    name: '성산일출봉',
    address: '제주 서귀포시 성산읍 일출로 284-12',
    category: 'landmark',
    themes: ['nature', 'ocean', 'drive'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '동절기 06:00~18:00, 춘·추절기 05:00~19:00, 하절기 04:30~20:00',
    feeText: '정상 코스 유료, 해안 산책로 무료',
    stayMinutes: { min: 90, max: 120 },
    bestTimeSlots: ['early-morning', 'morning'],
    bestVisitText: '이른 오전',
    tips: [
      '정상 코스는 계단 경사가 있어 운동화 착용이 편합니다.',
      '매월 첫째 월요일은 휴관이며 공휴일이면 다음 날 휴관합니다.',
    ],
    nearbyPlaceIds: ['seopjikoji', 'udo-island'],
    legacy: {
      hours: '동절기 06:00~18:00, 춘·추절기 05:00~19:00, 하절기 04:30~20:00',
      fee: '정상 코스 유료, 해안 산책로 무료',
      stayDuration: '1.5~2시간',
      bestVisitTime: '이른 오전',
      nearbyPlaceSlugs: ['seopjikoji', 'udo-island'],
      includedCourseSlugs: ['jeju-east-coast-1day'],
    },
  },
  seopjikoji: {
    id: 'seopjikoji',
    regionId: 'jeju',
    slug: 'seopjikoji',
    name: '섭지코지',
    address: '제주 서귀포시 성산읍 섭지코지로 262',
    category: 'landmark',
    themes: ['nature', 'ocean', 'drive', 'healing'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '연중 개방',
    feeText: '무료',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '오전 10시 이전 또는 늦은 오후',
    tips: [
      '해안 바람이 강한 날이 많아 얇은 겉옷을 챙기는 편이 좋습니다.',
      '성산일출봉과 묶어 보면 동선이 자연스럽습니다.',
    ],
    nearbyPlaceIds: ['seongsan-ilchulbong', 'udo-island'],
    legacy: {
      hours: '연중 개방',
      fee: '무료',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오전 10시 이전 또는 늦은 오후',
      nearbyPlaceSlugs: ['seongsan-ilchulbong', 'udo-island'],
      includedCourseSlugs: ['jeju-east-coast-1day'],
    },
  },
  'udo-island': {
    id: 'udo-island',
    regionId: 'jeju',
    slug: 'udo-island',
    name: '우도(해양도립공원)',
    address: '제주 제주시 우도면 삼양고수물길 1',
    category: 'island',
    themes: ['nature', 'ocean', 'drive', 'healing'],
    companions: ['couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '연중 개방',
    feeText: '입도 시간과 교통편은 선박 운영 상황에 따라 달라집니다.',
    stayMinutes: { min: 180, max: 240 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '오전 배편 입도',
    tips: [
      '성산포항 여객선 시간표를 먼저 확인해야 일정이 안정적입니다.',
      '섬 전체를 보려면 전기차·스쿠터·버스 등 이동 수단 선택이 중요합니다.',
    ],
    nearbyPlaceIds: ['seongsan-ilchulbong', 'seopjikoji'],
    legacy: {
      hours: '연중 개방',
      fee: '입도 시간과 교통편은 선박 운영 상황에 따라 달라집니다.',
      stayDuration: '3~4시간',
      bestVisitTime: '오전 배편 입도',
      nearbyPlaceSlugs: ['seongsan-ilchulbong', 'seopjikoji'],
      includedCourseSlugs: ['jeju-east-coast-1day'],
    },
  },
  osulloc: {
    id: 'osulloc',
    regionId: 'jeju',
    slug: 'osulloc',
    name: '오설록 티뮤지엄',
    address: '제주 서귀포시 안덕면 신화역사로 15',
    category: 'museum',
    themes: ['cafe', 'culture', 'healing', 'drive'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['all', 'rain-friendly', 'indoor'],
    hoursText: '09:00~18:00',
    feeText: '무료',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '오전 10시 전후',
    tips: [
      '기념품과 음료 주문 대기가 길어질 수 있어 여유 시간을 두는 편이 좋습니다.',
      '인근 녹차밭 산책까지 포함하면 체류 시간이 늘어납니다.',
    ],
    nearbyPlaceIds: ['hyeopjae-beach', 'hallim-park'],
    legacy: {
      hours: '09:00~18:00',
      fee: '무료',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오전 10시 전후',
      nearbyPlaceSlugs: ['hyeopjae-beach', 'hallim-park'],
      includedCourseSlugs: ['jeju-west-drive-1day'],
    },
  },
  'hyeopjae-beach': {
    id: 'hyeopjae-beach',
    regionId: 'jeju',
    slug: 'hyeopjae-beach',
    name: '협재해수욕장',
    address: '제주 제주시 한림읍 협재리 2497-1',
    category: 'beach',
    themes: ['ocean', 'nature', 'healing'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '상시 개방',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['afternoon', 'evening'],
    bestVisitText: '오후 2시 이후',
    tips: [
      '바닷색이 맑아 햇빛이 좋은 오후 시간대 만족도가 높습니다.',
      '바람이 강한 날은 해변보다 인근 카페 위주로 동선을 바꾸는 편이 편합니다.',
    ],
    nearbyPlaceIds: ['osulloc', 'hallim-park'],
    legacy: {
      hours: '상시 개방',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '오후 2시 이후',
      nearbyPlaceSlugs: ['osulloc', 'hallim-park'],
      includedCourseSlugs: ['jeju-west-drive-1day'],
    },
  },
  'hallim-park': {
    id: 'hallim-park',
    regionId: 'jeju',
    slug: 'hallim-park',
    name: '한림공원',
    address: '제주 제주시 한림읍 한림로 300',
    category: 'park',
    themes: ['nature', 'family', 'healing'],
    companions: ['parents', 'kids', 'family'],
    weatherFit: ['all', 'rain-friendly', 'indoor', 'outdoor'],
    hoursText: '09:00~18:00',
    feeText: '성인 15,000원, 청소년 11,000원, 어린이 10,000원',
    stayMinutes: { min: 90, max: 120 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '오후 3시 전',
    tips: [
      '정원이 넓어 편한 신발이 좋습니다.',
      '협재해변과 붙여 보면 이동 효율이 좋습니다.',
    ],
    nearbyPlaceIds: ['hyeopjae-beach', 'osulloc'],
    legacy: {
      hours: '09:00~18:00',
      fee: '성인 15,000원, 청소년 11,000원, 어린이 10,000원',
      stayDuration: '1.5~2시간',
      bestVisitTime: '오후 3시 전',
      nearbyPlaceSlugs: ['hyeopjae-beach', 'osulloc'],
      includedCourseSlugs: ['jeju-west-drive-1day'],
    },
  },
  ojukheon: {
    id: 'ojukheon',
    regionId: 'gangneung',
    slug: 'ojukheon',
    name: '오죽헌·시립박물관',
    address: '강원특별자치도 강릉시 율곡로3139번길 24',
    category: 'museum',
    themes: ['culture', 'history'],
    companions: ['solo', 'couple', 'friends', 'parents', 'family'],
    weatherFit: ['all', 'rain-friendly', 'indoor'],
    hoursText: '관람 09:00~18:00, 입장 09:00~17:00',
    feeText: '어른 3,000원, 청소년·군인 2,000원, 어린이 1,000원',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['morning', 'afternoon'],
    bestVisitText: '오전 10시 전후',
    tips: [
      '1월 1일, 설날, 추석 당일은 실내 전시실 운영 여부를 먼저 확인하는 편이 좋습니다.',
      '강릉 대표 문화유산 동선의 출발점으로 잡기 좋습니다.',
    ],
    nearbyPlaceIds: ['gyeongpo-beach', 'anmok-beach'],
    legacy: {
      hours: '관람 09:00~18:00, 입장 09:00~17:00',
      fee: '어른 3,000원, 청소년·군인 2,000원, 어린이 1,000원',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오전 10시 전후',
      nearbyPlaceSlugs: ['gyeongpo-beach', 'anmok-beach'],
      includedCourseSlugs: ['gangneung-coast-1day'],
    },
  },
  'gyeongpo-beach': {
    id: 'gyeongpo-beach',
    regionId: 'gangneung',
    slug: 'gyeongpo-beach',
    name: '경포해변',
    address: '강원특별자치도 강릉시 안현동 산1',
    category: 'beach',
    themes: ['ocean', 'healing', 'drive'],
    companions: ['solo', 'couple', 'friends', 'family'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '개방 06:00~24:00',
    feeText: '무료',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['afternoon', 'evening'],
    bestVisitText: '오후 4시 이후',
    tips: [
      '해변 산책과 경포호 주변 동선을 함께 잡으면 이동이 효율적입니다.',
      '여름 성수기에는 수영 가능 시간이 별도로 운영됩니다.',
    ],
    nearbyPlaceIds: ['ojukheon', 'anmok-beach'],
    legacy: {
      hours: '개방 06:00~24:00',
      fee: '무료',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오후 4시 이후',
      nearbyPlaceSlugs: ['ojukheon', 'anmok-beach'],
      includedCourseSlugs: ['gangneung-coast-1day'],
    },
  },
  'anmok-beach': {
    id: 'anmok-beach',
    regionId: 'gangneung',
    slug: 'anmok-beach',
    name: '안목해변',
    address: '강원특별자치도 강릉시 창해로14번길 20-1',
    category: 'cafe-area',
    themes: ['ocean', 'cafe', 'healing'],
    companions: ['solo', 'couple', 'friends'],
    weatherFit: ['sunny', 'cloudy', 'outdoor'],
    hoursText: '개방 06:00~24:00',
    feeText: '무료',
    stayMinutes: { min: 60, max: 120 },
    bestTimeSlots: ['evening', 'night'],
    bestVisitText: '해질 무렵',
    tips: [
      '카페거리와 함께 보기 좋은 해변이라 저녁 시간대 체류가 길어질 수 있습니다.',
      '주말에는 주차보다 도보 이동이 더 빠를 때가 많습니다.',
    ],
    nearbyPlaceIds: ['gyeongpo-beach', 'ojukheon'],
    legacy: {
      hours: '개방 06:00~24:00',
      fee: '무료',
      stayDuration: '1~2시간',
      bestVisitTime: '해질 무렵',
      nearbyPlaceSlugs: ['gyeongpo-beach', 'ojukheon'],
      includedCourseSlugs: ['gangneung-coast-1day'],
    },
  },
  'chodang-sundubu-village': {
    id: 'chodang-sundubu-village',
    regionId: 'gangneung',
    slug: 'chodang-sundubu-village',
    name: '초당순두부마을',
    address: '강원특별자치도 강릉시 초당순두부길 일대',
    category: 'village',
    themes: ['food', 'cafe', 'healing'],
    companions: ['solo', 'couple', 'friends', 'parents', 'family'],
    weatherFit: ['all', 'rain-friendly', 'indoor'],
    hoursText: '식당별 상이 (대부분 07:00~20:00)',
    feeText: '식당별 상이',
    stayMinutes: { min: 60, max: 90 },
    bestTimeSlots: ['morning', 'lunch'],
    bestVisitText: '오전 11시 이전',
    tips: [
      '주요 식당은 점심 시간에 대기가 길어질 수 있습니다.',
      '경포호, 허균허난설헌 기념공원과 묶어 이동하기 좋습니다.',
    ],
    nearbyPlaceIds: ['gyeongpo-beach', 'anmok-beach'],
    legacy: {
      hours: '식당별 상이 (대부분 07:00~20:00)',
      fee: '식당별 상이',
      stayDuration: '1~1.5시간',
      bestVisitTime: '오전 11시 이전',
      nearbyPlaceSlugs: ['gyeongpo-beach', 'anmok-beach'],
      includedCourseSlugs: ['gangneung-cafe-healing-1day'],
    },
  },
};

export const PLACE_IDS = Object.keys(PLACES);
export const placeList = PLACE_IDS.map((id) => PLACES[id]);
